services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    container_name: nestjs_container
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      - DB_HOST=postgres # Use "postgres" como o nome do serviço do banco de dados
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
