version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - ./.env

  server:
    build:
      context: ./
    container_name: nestjs_container
    restart: always
    command: sh -c "npm install && until nc -z postgres 5432; do sleep 1; done && npm run start:dev"
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - ./.env

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
